version: "3.8"
services:
  web:
    image: thaipat/spl_web
    ports:
      - "11480:3000"
    stdin_open: true
    tty: true
    
  app:
    container_name: app
    image: thaipat/spl_back
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - mysql_data:/var/lib/mysql

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Smart_Parking_Lot_db
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local
